SGI/Apps/Indicadores/urls.py
from django.contrib import admin
from django.urls import path
from Apps.Indicadores import views
import re

app_name = "indicadores"

urlpatterns = [
    path('', views.indicadores_index,name = 'index'),
    path('indicadorform/',views.Indicador_Create.as_view(), name = 'crear_indicador'),
    path('listarindicador/',views.Indicador_List.as_view(), name = 'listar_indicador'),
    path('actualizarindicador/<pk>/',views.Indicador_Update.as_view(), name = 'actualizar_indicador'),
    path('eliminarindicador/<pk>/',views.Indicador_Delete.as_view(), name = 'eliminar_indicador'),

    path('listarvalor/',views.Valor_Indicador_List.as_view(), name = 'listar_valor_indicador'),
    path('crearvalor/',views.Valor_Indicador_Create.as_view(), name = 'crear_valor_indicador'),
    path('actualizarvalor/<pk>',views.Valor_Indicador_Update.as_view(), name = 'actualizar_valor_indicador'),
    path('eliminarvalor/<pk>',views.Valor_Indicador_Delete.as_view(), name = 'eliminar_valor_indicador'),
    

    path('listaralarma/',views.Alarma_List.as_view(), name = 'listar_alarma'),
    path('crearalarma/',views.Alarma_Create.as_view(), name = 'crear_alarma'),
    path('eliminaralarma/<pk>',views.Alarma_Delete.as_view(), name = 'eliminar_alarma'),
    path('actualizaralarma/<pk>',views.Alarma_Update.as_view(), name = 'actualizar_alarma'),

 

    # path('alarmaform/', views.alarma_form, name = 'crear_alarma'),
    # path('medidaform/', views.medida_form, name = 'crear_medida'),
    # path('valorindicadorform/', views.valor_indicador_form, name = 'crear_valor_de_indicador'),
    path('base/',views.base, name= 'base'),
]

SGI/SGI/urls.py
from django.contrib import admin
from django.urls import include,path
from Apps.Indicadores import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Apps.Indicadores.urls', namespace='indicadores')),
    path('usuario/', include('Apps.usuario.urls', namespace='usuario')),
]

SGI/Apps/Indicadores/models.py
from pyexpat import model
from tkinter import CASCADE
from django.db import models

# Create your models here.

class Indicador(models.Model):
    nombre = models.CharField(max_length=50)
    tipo = models.CharField(max_length=50)
    descripcion = models.TextField()
    estado = models.CharField(max_length=30)
    fecha_estado = models.DateField()
    min_valor = models.FloatField()
    med_valor = models.FloatField()
    max_valor = models.FloatField()
    valor_critico = models.FloatField()
    frecuencia = models.IntegerField()
    irregularidades = models.TextField()
    unidad_valor = models.CharField(max_length=10) # Revisar esto
    correos = models.EmailField()


    def __str__(self) -> str:
        return self.nombre




class Valor_Indicador(models.Model):
    valor = models.FloatField()
    valor_en_porcentaje = models.CharField(max_length=10)
    fecha = models.DateField()
    indicador = models.ForeignKey(Indicador, null=True,blank=True, on_delete= models.CASCADE) # 1 Indicador-- * valores

class Alarma(models.Model):
    valor_alerta = models.FloatField()       
    nivel_alarma = models.IntegerField()
    estado_alarma = models.BooleanField()
    fecha = models.DateField()

    # 1 Alarma es generada por 1/* valores de indicadores
    valor_de_indicador = models.ForeignKey(Valor_Indicador, null=True,blank=True, on_delete= models.CASCADE) # 1 Indicador-- * valores

class Medida(models.Model):
    medidas_tomadas = models.TextField() 
    fecha_de_la_medida = models.DateField()
    indicador = models.ForeignKey(Indicador, null=True,blank=True, on_delete= models.CASCADE) # 1 Indicador-- * valores
    alarma = models.ForeignKey(Alarma, null=True,blank=True, on_delete= models.CASCADE) # 1 Indicador-- * valores
    

SGI/Apps/Indicadores/views.py
from re import L
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from Apps.Indicadores.form import Alarma_Form, Valor_Indicador_Form, Medida_Form,Indicador_Form
from Apps.Indicadores.models import Indicador,Valor_Indicador, Alarma, Medida
# Create your views here.

# vistas basadas en clases

# Indicador..........
class Indicador_List(ListView):
    model = Indicador
    template_name: str = 'indicadores/indicador_list.html'

class Indicador_Create(CreateView):
    model = Indicador
    form_class= Indicador_Form
    template_name: str = 'indicadores/indicador_form.html'
    success_url= reverse_lazy('indicadores:listar_indicador')

class Indicador_Update(UpdateView):
    model = Indicador
    fields = '__all__'
    form_class = Indicador_Form
    template_name: str = 'indicadores/indicador_form.html'
    success_url = reverse_lazy('indicadores:listar_indicador')


class Indicador_Delete(DeleteView):
    model = Indicador
    fields = '__all__'   
    template_name: str = 'indicadores/indicador_delete.html'
    success_url = reverse_lazy('indicadores:listar_indicador')



# Valor Indicador
class Valor_Indicador_List(ListView):
    model = Valor_Indicador
    template_name: str = 'indicadores/valor_indicador/valor_indicador_list.html'

class Valor_Indicador_Create(CreateView):
    model = Valor_Indicador
    template_name: str = 'indicadores/valor_indicador/valor_indicador_form.html'
    form_class = Valor_Indicador_Form
    #second_form_class = Indicador_Form
    success_url= reverse_lazy('indicadores:listar_valor_indicador')

    # def get_context_data(self, **kwargs):
    #     context = super(Valor_Indicador_Create, self).get_context_data(**kwargs)
    #     if 'form' not in context:
    #         context['form'] = self.form_class(self.request.GET)
    #     if 'form2' not in context:
    #         context['form2'] = self.second_form_class(self.request.GET)
    #     return context  

    # def post(self, request, *args, **kwargs):
    #     self.object = self.get_object
    #     form = self.form_class(request.POST)
    #     form2 = self.second_form_class(request.POST)

    #     if form.is_valid() and form2.is_valid():
    #         solicitud = form.save(commit = False)
    #         solicitud.persona = form2.save() 
    #         solicitud.save()
    #         return HttpResponseRedirect(self.get_success_url())
    #     else :
    #         return self.render_to_response(self.get_context_data(form = form, form2 = form))         


class Valor_Indicador_Update(UpdateView):
    model = Valor_Indicador
    # fields = '__all__'
    form_class = Valor_Indicador_Form
    template_name: str = 'indicadores/valor_indicador/valor_indicador_form.html'
    success_url = reverse_lazy('indicadores:listar_valor_indicador')    


class Valor_Indicador_Delete(DeleteView):
    model = Valor_Indicador
    fields = '__all__'
    template_name: str = 'indicadores/valor_indicador/valor_indicador_delete.html'
    success_url = reverse_lazy('indicadores:listar_valor_indicador')    



class Alarma_Create(CreateView):
    model = Alarma
    form_class = Alarma_Form
    template_name: str = 'indicadores/alarma/alarma_form.html'
    success_url = reverse_lazy('indicadores:listar_alarma')

class Alarma_Delete(DeleteView):
    model = Alarma
    fields = '__all__'
    template_name: str = 'indicadores/alarma/alarma_delete.html'
    success_url = reverse_lazy('indicadores:listar_alarma')    


class Alarma_List(ListView):
    model = Alarma
    template_name: str = 'indicadores/alarma/alarma_list.html'

class Alarma_Update(UpdateView):
    model = Alarma
    # fields = '__all__'
    form_class = Alarma_Form
    template_name: str = 'indicadores/alarma/alarma_form.html'
    success_url = reverse_lazy('indicadores:listar_alarma')    



# vistas basadas en funciones

def indicadores_index(request):
    return render(request,'indicadores/index.html')

def indicador_list(request):
    indicador = Indicador.objects.all()
    contexto = {'indicadores' : indicador}
    return render(request,'indicadores/indicador_list.html', contexto)

def indicator_update(request, id_indicador):
    indicador = Indicador.objects.get(id = id_indicador)
    if request.method == 'GET':
        form = Indicador_Form(instance=indicador)
    else:
        form = Indicador_Form(request.POST, instance=indicador)
        if form.is_valid():
            form.save()    
        return redirect('indicadores:listar_indicador') 
    return render(request, 'indicadores/indicador_form.html', {'form':form} )       

def indicator_delete(request, id_indicador):
    indicador = Indicador.objects.get(id = id_indicador)
    if request.method == 'POST':
        indicador.delete()
        return redirect('indicadores:listar_indicador')
    return render(request, 'indicadores/indicador_delete.html', {'indicador':indicador} )       



def alarma_form(request):
    if request.method == 'POST':
        form =  Alarma_Form(request.POST)
        if form.is_valid():
            form.save()
        return redirect('Indicadores:index')    
    else:
        form = Alarma_Form()   
    return render(request,'indicadores/alarma_form.html', {'form':form})     

def valor_indicador_form(request):
    if request.method == 'POST':
        form =  Valor_Indicador_Form(request.POST)
        if form.is_valid():
            form.save()
        return redirect('index')    
    else:
        form = Valor_Indicador_Form()   
    return render(request,'indicadores/valor_indicador_form.html', {'form':form})     

def medida_form(request):
    if request.method == 'POST':
        form =  Medida_Form(request.POST)
        if form.is_valid():
            form.save()
        return redirect('Indicadores:index')    
    else:
        form = Medida_Form()   
    return render(request,'indicadores/medida_form.html', {'form':form})     


def indicadores_form(request):
    if request.method == 'POST':
        form =  Indicador_Form(request.POST)
        if form.is_valid():
            form.save()
        return redirect('indicadores:listar_indicador')    
    else:
        form = Indicador_Form()   
    return render(request,'indicadores/indicador_form.html', {'form':form})     

def base(request):
    return render(request,'base/base.html')    

SGI/templates/indicadores/index.html
{% extends 'base/base.html' %}

SGI/templates/indicadores/indicador_delete.html
{% extends 'base/base.html' %}

{% block content%}
<form method="post">
    {% csrf_token %}
    <h3>Desea eliminar el registro de {{object.nombre}}</h3> 

    <button class="btm btn-danger" type = "submit">Si, eliminar</button>
    <a class="btn btn-default" href="{% url 'indicadores:listar_indicador' %}">
        Cancelar
    </a>
</form>

{%endblock%}

SGI/templates/indicadores/indicador_form.html
{% extends 'base/base.html' %}

{% block content%}
<form method="post">
    {% csrf_token %} 
    {{form.as_p}}
    <button type = "submit">Guardar</button>
</form>

{%endblock%}

SGI/templates/indicadores/indicador_list.html
{% extends 'base/base.html'%}

{% block content%}
<table class = "table">
    <thead>
        <tr>
            <td>Nombre</td>
            <td>Tipo</td>
            <td>Descripcion</td>
            <td>Estado</td>
            <td>Fecha de estado</td>
            <td>Valor Minimo</td>
            <td>Valor Medio</td>
            <td>Valor Maximo</td>
            <td>Valor Critico</td>
            <td>Frecuencia</td>
            <td>Irregularidades</td>
            <td>Unidad de valor</td>
            <td>Correos</td>
        </tr>

    </thead>
    <tbody>
        {% if object_list %}
        {% for indicador in object_list %}
        <tr>
            <td>{{indicador.nombre}}</td>
            <td>{{indicador.tipo}}</td>
            <td>{{indicador.descripcion}}</td>
            <td>{{indicador.estado}}</td>
            <td>{{indicador.fecha_estado}}</td>
            <td>{{indicador.min_valor}}</td>
            <td>{{indicador.med_valor}}</td>
            <td>{{indicador.max_valor}}</td>
            <td>{{indicador.valor_critico}}</td>
            <td>{{indicador.frecuencia}}</td>
            <td>{{indicador.irregularidades}}</td>
            <td>{{indicador.unidad_valor}}</td>
            <td>{{indicador.correos}}</td>
            <td>
                <a class="btn btn-primary" href="{% url  'indicadores:actualizar_indicador' indicador.id %}">Editar</a>
                <a class="btn btn-primary" href="{% url  'indicadores:eliminar_indicador' indicador.id %}">Eliminar</a>
            </td>
        </tr>
        {% endfor%}

        {% else %}
        <h1>No hay registros de indicadores</h1>

        {% endif %}
    </tbody>
</table>
{%endblock%}

SGI/templates/indicadores/indicadores_form.html
{% extends 'base/base.html' %}

{% block content%}
<form method="post">
    {% csrf_token %} 
    {{form.as_p}}
    <button type = "submit"></button>
</form>
{%endblock%}